### ISSUE TITLE
service entirely down?

### ISSUE THREAD

**Issue by sun-geo** [PeWu/osm-history#13]
Page function seems currently down.
Message: _"Error loading history."_, see:
![pewu down](https://user-images.githubusercontent.com/47290585/75870275-0fbe4380-5e0b-11ea-9ca4-20d2b9fc22b7.png)

**Comment by PeWu** [comment]
This was broken by https://github.com/openstreetmap/openstreetmap-website/pull/2485
The OSM API started returning JSON instead of XML responses.

Unfortunately, osm-history sends an `accept: application/json` header, probably a default somewhere. The solution is to send an `accept: */*` header when calling the OSM API. This looks like a small change but I'll be able to do it only tomorrow. I'd merge a PR if someone did the change earlier.

As a workaround, log in to OSM using the _Login_ link at the bottom of osm-history. This uses a different path for making requests and it sends correct headers.

JOSM also had this problem and it's fixed in https://josm.openstreetmap.de/changeset/15968/josm and https://josm.openstreetmap.de/changeset/15969/josm

**Comment by mmd-osm** [comment]
> JOSM also had this problem and it's fixed

Nope, that's not the case. We implemented a special case handling for JOSM, and JOSM never experienced any issue.

**Comment by sun-geo** [comment]
Thank you!
