### ISSUE TITLE
Display added/removed relation members instead of just count

### ISSUE THREAD

**Issue by DavidKarlas** [PeWu/osm-history#17]
Hi,

I think it would be pretty nice if instead of just members count change it would list added and removed members. And probably for "role" changes mark it as modification... Similar UI as for Tags...
Big admin relations histories today look something like this:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/774791/211181289-99c71283-a213-4b4d-8dd1-b14cdf01d0a4.png">

How hard do you think this would be? Would it hurt perf a lot?

Thanks,
David

**Comment by LaoshuBaby** [comment]
Feature request, I found this repository here because I want to open a same issue if I haven't found this one. Thank you!

I really hope to display the id and type of each changed member in the form of a list, and it is best to provide a link, click to open the pewu history page of this member in a new tab

**Comment by DavidKarlas** [comment]
Ideally there would be link to member added/removed.
