### ISSUE TITLE
Add JOSM to panel with editors

### ISSUE THREAD

**Issue by javnik36** [PeWu/osm-history#3]
Could you add link to edit in JOSM via remote control?

I think the most interesting here will be [Load&zoom](https://josm.openstreetmap.de/wiki/Help/Preferences/RemoteControl#load_and_zoom) function.
Here will be needed bbox calculation of osm object. But when it's too complicated(for me it is :), that's why I'm not PRing), adding just [loading an object](https://josm.openstreetmap.de/wiki/Help/Preferences/RemoteControl#load_object) will be fine.

**Comment by javnik36** [comment]
Thanks! You're great!
But I have spotted a problem with this function. After clicking on JOSM, apparently pops out _JOSM request failed._ The link seems Ok(when copy paste it, all is working), but there is a problem with angular? I assume it don't likes the http request, when site is on https.

That's what my Chrome Dev Tools shows:
![image](https://cloud.githubusercontent.com/assets/8407785/18485154/ee095920-79eb-11e6-98ac-0448cc431e32.png)

It is solvable?

**Comment by PeWu** [comment]
The problem is that the page is hosted on an HTTPS site and the JOSM link is HTTP. This is the browser that is complaining.
There is a workaround: https://pearsonnacommunity.force.com/support/s/article/How-to-display-mixed-content-with-Google-Chrome-Internet-Explorer-or-Firefox-1408394589290
There should be a better way to do it, maybe opening the link in a new tab.

**Comment by javnik36** [comment]
Hmmm...ok, thanks for explanation, good to know. Easiest workaround is hosting this on non-https :smiley:
